<?php
/**
 * Plugin Name: Alt Fixes AI
 * Description: AI-assisted image alt text suggestions with browser-local vision, WordPress context and human approval.
 * Version: 1.0.0
 * Author: beebus-builds
 * License: GPL-2.0-or-later
 */
if (!defined('ABSPATH')) exit;
define('ALT_FIXES_VERSION','1.0.0');define('ALT_FIXES_OPTION','alt_fixes_settings');define('ALT_FIXES_PATH',plugin_dir_path(__FILE__));define('ALT_FIXES_URL',plugin_dir_url(__FILE__));
require_once ALT_FIXES_PATH.'includes/providers/interface-alt-fixes-provider.php';require_once ALT_FIXES_PATH.'includes/providers/class-alt-fixes-openai-provider.php';require_once ALT_FIXES_PATH.'includes/class-alt-fixes-context.php';require_once ALT_FIXES_PATH.'includes/class-alt-fixes-engine.php';require_once ALT_FIXES_PATH.'includes/class-alt-fixes-queue.php';require_once ALT_FIXES_PATH.'includes/class-alt-fixes-browser.php';
register_activation_hook(__FILE__,'alt_fixes_activate');function alt_fixes_activate(){Alt_Fixes_Queue::install();}register_deactivation_hook(__FILE__,'alt_fixes_deactivate');function alt_fixes_deactivate(){Alt_Fixes_Queue::unschedule_maintenance();}add_action('plugins_loaded',function(){Alt_Fixes_Queue::install();});add_action('init',function(){Alt_Fixes_Queue::schedule_maintenance();},20);
add_action('admin_menu',function(){$hook=add_media_page('Alt Fixes AI','Alt Fixes AI','manage_options','alt-fixes-ai','alt_fixes_render_admin');add_action("admin_enqueue_scripts-{$hook}",'alt_fixes_enqueue_admin_assets');});
function alt_fixes_enqueue_admin_assets(){wp_enqueue_style('alt-fixes-admin',ALT_FIXES_URL.'admin/assets/admin.css',[],ALT_FIXES_VERSION);wp_enqueue_script('alt-fixes-admin',ALT_FIXES_URL.'admin/assets/admin.js',[],ALT_FIXES_VERSION,true);wp_enqueue_script('alt-fixes-browser-ai',ALT_FIXES_URL.'admin/assets/browser-ai.js',[],ALT_FIXES_VERSION,true);wp_localize_script('alt-fixes-admin','AltFixesAdmin',['root'=>trailingslashit(rest_url('alt-fixes/v1')),'nonce'=>wp_create_nonce('wp_rest'),'provider'=>get_option(ALT_FIXES_OPTION,['provider'=>'browser-local'])['provider']??'browser-local']);}
add_action('admin_init',function(){register_setting('alt_fixes',ALT_FIXES_OPTION,['sanitize_callback'=>function($value){$provider=sanitize_key($value['provider']??'browser-local');if(!in_array($provider,['browser-local','openai'],true))$provider='browser-local';return['provider'=>$provider,'api_key'=>sanitize_text_field($value['api_key']??''),'model'=>sanitize_text_field($value['model']??'gpt-5.6-luna')];}]);});
add_action('rest_api_init',function(){$routes=[['/scan','GET','alt_fixes_scan'],['/analytics','GET','alt_fixes_analytics'],['/suggest/(?P<id>\d+)','POST','alt_fixes_suggest'],['/approve/(?P<id>\d+)','POST','alt_fixes_approve'],['/auto-approve/(?P<id>\d+)','POST','alt_fixes_auto_approve'],['/skip/(?P<id>\d+)','POST','alt_fixes_skip'],['/bulk-suggest','POST','alt_fixes_bulk_suggest'],['/bulk-approve','POST','alt_fixes_bulk_approve'],['/bulk-auto-approve','POST','alt_fixes_bulk_auto_approve'],['/jobs/(?P<job_id>\d+)','GET','alt_fixes_job_status'],['/jobs/(?P<job_id>\d+)/retry','POST','alt_fixes_retry_job']];foreach($routes as[$route,$method,$callback])register_rest_route('alt-fixes/v1',$route,['methods'=>$method,'permission_callback'=>'alt_fixes_rest_permission','callback'=>$callback]);});
function alt_fixes_rest_permission(){return current_user_can('manage_options');}
function alt_fixes_get_status($id,$alt=null,$suggestion=null){$stored=(string)get_post_meta($id,'_alt_fixes_status',true);if($stored!=='')return $stored;if($alt===null)$alt=(string)get_post_meta($id,'_wp_attachment_image_alt',true);if($suggestion===null)$suggestion=(string)get_post_meta($id,'_alt_fixes_suggestion',true);return trim($alt)===''?($suggestion!==''?'suggested':'missing'):'approved';}
function alt_fixes_analysis($id){$analysis=get_post_meta($id,'_alt_fixes_analysis',true);return is_array($analysis)?$analysis:[];}
function alt_fixes_analytics(WP_REST_Request $request){return rest_ensure_response(Alt_Fixes_Learning::analytics());}
function alt_fixes_latest_job_map($ids){global $wpdb;$ids=array_values(array_filter(array_map('absint',(array)$ids)));if(!$ids)return[];$table=Alt_Fixes_Queue::table_name();$placeholders=implode(',',array_fill(0,count($ids),'%d'));$sql=$wpdb->prepare("SELECT j.* FROM {$table} j INNER JOIN (SELECT attachment_id,MAX(id) id FROM {$table} WHERE attachment_id IN ({$placeholders}) GROUP BY attachment_id) latest ON latest.id=j.id",$ids);$rows=$wpdb->get_results($sql,ARRAY_A);$map=[];foreach((array)$rows as$row)$map[(int)$row['attachment_id']=$row;return$map;}
function alt_fixes_scan(WP_REST_Request $request){$page=max(1,absint($request->get_param('page'))?:1);$per_page=min(100,max(1,absint($request->get_param('per_page'))?:24));$status=sanitize_key($request->get_param('status')?:'all');$allowed=['all','missing','queued','processing','suggested','review','auto','failed','approved','skipped'];if(!in_array($status,$allowed,true))$status='all';$ids=get_posts(['post_type'=>'attachment','post_mime_type'=>'image','post_status'=>'inherit','posts_per_page'=>-1,'fields'=>'ids','orderby'=>'ID','order'=>'DESC']);$filtered=[];foreach($ids as$id){$alt=(string)get_post_meta($id,'_wp_attachment_image_alt',true);$suggestion=(string)get_post_meta($id,'_alt_fixes_suggestion',true);$analysis=alt_fixes_analysis($id);$item_status=alt_fixes_get_status($id,$alt,$suggestion);$decision=$analysis['approval']['decision']??'';if($status==='review'&&$decision!=='review')continue;if($status==='auto'&&$decision!=='pass')continue;if(in_array($status,['review','auto'],true)){$filtered[]=$id;continue;}if($status==='all'||$item_status===$status)$filtered[]=$id;}$total=count($filtered);$pages=$total?(int)ceil($total/$per_page):0;$page_ids=array_slice($filtered,($page-1)*$per_page,$per_page);$jobs=alt_fixes_latest_job_map($page_ids);$items=[];foreach($page_ids as$id){$alt=(string)get_post_meta($id,'_wp_attachment_image_alt',true);$suggestion=(string)get_post_meta($id,'_alt_fixes_suggestion',true);$analysis=alt_fixes_analysis($id);$job=$jobs[(int)$id]??[];$items[]=['id'=>(int)$id,'title'=>get_the_title($id),'url'=>wp_get_attachment_image_url($id,'medium'),'alt'=>$alt,'suggestion'=>$suggestion,'status'=>alt_fixes_get_status($id,$alt,$suggestion),'purpose'=>$analysis['purpose']??null,'decorative'=>!empty($analysis['decorative']),'confidence'=>isset($analysis['confidence'])?(float)$analysis['confidence']:null,'quality_score'=>isset($analysis['quality_score'])?(int)$analysis['quality_score']:null,'quality_flags'=>!empty($analysis['quality_flags'])?(array)$analysis['quality_flags']:[],'approval'=>$analysis['approval']??null,'ocr_text'=>$analysis['ocr_text']??'','review_reason'=>$analysis['review_reason']??'','evidence'=>$analysis['evidence']??'','decision_trace'=>$analysis['decision_trace']??[],'model'=>$analysis['model']??'','job_id'=>isset($job['id'])?(int)$job['id']:null,'job_status'=>$job['status']??null,'error'=>$job['error']??'','attempts'=>isset($job['attempts'])?(int)$job['attempts']:0];}return rest_ensure_response(['items'=>$items,'page'=>$page,'per_page'=>$per_page,'total'=>$total,'pages'=>$pages,'analytics'=>Alt_Fixes_Learning::analytics()]);}
function alt_fixes_validate_image($id){return get_post_type($id)==='attachment'&&strpos((string)get_post_mime_type($id),'image/')===0;}
function alt_fixes_store_suggestion($id,$result){$suggestion=(string)($result['suggestion']??$result['alt']??'');if($suggestion!==''||(!empty($result['analysis']['decorative']))){update_post_meta($id,'_alt_fixes_suggestion',sanitize_text_field($suggestion));update_post_meta($id,'_alt_fixes_status','suggested');}if(!empty($result['analysis'])&&is_array($result['analysis']))update_post_meta($id,'_alt_fixes_analysis',$result['analysis']);return$suggestion;}
function alt_fixes_suggest(WP_REST_Request $request){$id=absint($request['id']);if(!alt_fixes_validate_image($id))return new WP_Error('invalid_image','The requested attachment is not an image.',['status'=>400]);$settings=get_option(ALT_FIXES_OPTION,[]);if(($settings['provider']??'browser-local')==='browser-local')return new WP_Error('browser_provider','Browser-local AI must be run from the Alt Fixes dashboard.',['status'=>409]);$result=Alt_Fixes_Engine::suggest($id);if(is_wp_error($result))return$result;alt_fixes_store_suggestion($id,$result);return rest_ensure_response($result);}
function alt_fixes_approve(WP_REST_Request $request){$id=absint($request['id']);if(!alt_fixes_validate_image($id))return new WP_Error('invalid_attachment','The requested attachment does not exist.',['status'=>404]);$alt=sanitize_text_field($request->get_param('alt'));if($alt==='')$alt=(string)get_post_meta($id,'_alt_fixes_suggestion',true);if($alt==='')return new WP_Error('empty_alt','No alt text supplied.',['status'=>400]);update_post_meta($id,'_wp_attachment_image_alt',$alt);update_post_meta($id,'_alt_fixes_status','approved');delete_post_meta($id,'_alt_fixes_suggestion');return rest_ensure_response(['id'=>$id,'alt'=>$alt,'status'=>'approved','approved'=>true,'approval_mode'=>'human']);}
function alt_fixes_auto_approve(WP_REST_Request $request){$id=absint($request['id']);if(!alt_fixes_validate_image($id))return new WP_Error('invalid_image','The requested attachment is not an image.',['status'=>400]);$analysis=alt_fixes_analysis($id);$approval=$analysis['approval']??[];if(empty($approval['auto_approvable']))return new WP_Error('review_required','This image does not meet the automatic approval gate.',['status'=>409,'approval'=>$approval]);$alt=(string)get_post_meta($id,'_alt_fixes_suggestion',true);if($alt===''&&!(!empty($analysis['decorative'])))return new WP_Error('empty_alt','No safe suggestion is available for automatic approval.',['status'=>400]);update_post_meta($id,'_wp_attachment_image_alt',sanitize_text_field($alt));update_post_meta($id,'_alt_fixes_status','approved');delete_post_meta($id,'_alt_fixes_suggestion');Alt_Fixes_Learning::record_auto_approval();return rest_ensure_response(['id'=>$id,'alt'=>$alt,'status'=>'approved','approved'=>true,'approval_mode'=>'automatic','approval'=>$approval]);}
function alt_fixes_skip(WP_REST_Request $request){$id=absint($request['id']);if(!alt_fixes_validate_image($id))return new WP_Error('invalid_image','The requested attachment is not an image.',['status'=>400]);update_post_meta($id,'_alt_fixes_status','skipped');return rest_ensure_response(['id'=>$id,'status'=>'skipped']);}
function alt_fixes_bulk_suggest(WP_REST_Request $request){$ids=$request->get_param('ids');if(!is_array($ids))return new WP_Error('invalid_ids','IDs must be an array.',['status'=>400]);$ids=array_values(array_unique(array_filter(array_map('absint',$ids))));if(!$ids||count($ids)>500)return new WP_Error('batch_limit','Select between 1 and 500 images per queue batch.',['status'=>400]);$job_ids=Alt_Fixes_Queue::enqueue($ids);if(!$job_ids)return new WP_Error('queue_error','No valid images could be queued.',['status'=>400]);return rest_ensure_response(['queued'=>count($job_ids),'job_ids'=>$job_ids,'progress'=>Alt_Fixes_Queue::get_progress($job_ids)]);}
function alt_fixes_bulk_auto_approve(WP_REST_Request $request){$ids=$request->get_param('ids');if(!is_array($ids)||!$ids)return new WP_Error('invalid_ids','IDs must be supplied.',['status'=>400]);if(count($ids)>100)return new WP_Error('batch_limit','Auto-approve at most 100 images per batch.',['status'=>400]);$results=[];$skipped=[];foreach(array_unique(array_filter(array_map('absint',$ids)))as$id){if(!alt_fixes_validate_image($id)){$skipped[]=['id'=>$id,'reason'=>'invalid_image'];continue;}$analysis=alt_fixes_analysis($id);$approval=$analysis['approval']??[];if(empty($approval['auto_approvable'])){$skipped[]=['id'=>$id,'reason'=>'review_required','approval'=>$approval];continue;}$alt=(string)get_post_meta($id,'_alt_fixes_suggestion',true);if($alt===''&&!empty($analysis['decorative']))$alt='';elseif($alt===''){$skipped[]=['id'=>$id,'reason'=>'empty_alt'];continue;}update_post_meta($id,'_wp_attachment_image_alt',sanitize_text_field($alt));update_post_meta($id,'_alt_fixes_status','approved');delete_post_meta($id,'_alt_fixes_suggestion');$results[]=['id'=>$id,'alt'=>$alt,'approved'=>true,'approval_mode'=>'automatic'];}if($results)for($i=0;$i<count($results);$i++)Alt_Fixes_Learning::record_auto_approval();return rest_ensure_response(['approved'=>count($results),'skipped'=>count($skipped),'results'=>$results,'skipped_items'=>$skipped]);}
function alt_fixes_bulk_approve(WP_REST_Request $request){$items=$request->get_param('items');if(!is_array($items)||!$items)return new WP_Error('invalid_items','Items must be supplied.',['status'=>400]);if(count($items)>25)return new WP_Error('batch_limit','Approve at most 25 images per batch.',['status'=>400]);$results=[];foreach($items as$item){$id=absint($item['id']??0);$alt=sanitize_text_field($item['alt']??'');if(!alt_fixes_validate_image($id)||$alt==='')continue;update_post_meta($id,'_wp_attachment_image_alt',$alt);update_post_meta($id,'_alt_fixes_status','approved');delete_post_meta($id,'_alt_fixes_suggestion');$results[]=['id'=>$id,'approved'=>true,'alt'=>$alt,'approval_mode'=>'human'];}return rest_ensure_response(['results'=>$results]);}
function alt_fixes_render_admin(){$settings=get_option(ALT_FIXES_OPTION,[]);$provider=$settings['provider']??'browser-local';?><div class="wrap"><h1>Alt Fixes AI</h1><p>Analyze your media library with free browser-local vision inference, WordPress context and human review.</p><form method="post" action="options.php"><?php settings_fields('alt_fixes');?><table class="form-table"><tr><th>AI provider</th><td><select name="<?php echo esc_attr(ALT_FIXES_OPTION);?>[provider]"><option value="browser-local" <?php selected($provider,'browser-local');?>>Free browser-local AI (recommended)</option><option value="openai" <?php selected($provider,'openai');?>>OpenAI (optional paid provider)</option></select><p class="description">Browser-local mode needs no API key. The vision model runs in the browser and is cached after its first download.</p></td></tr><?php if($provider==='openai'):?><tr><th>API key</th><td><input type="password" class="regular-text" name="<?php echo esc_attr(ALT_FIXES_OPTION);?>[api_key]" value="<?php echo esc_attr($settings['api_key']??''); ?>" autocomplete="off"></td></tr><tr><th>Vision model</th><td><input type="text" class="regular-text" name="<?php echo esc_attr(ALT_FIXES_OPTION);?>[model]" value="<?php echo esc_attr($settings['model']??'gpt-5.6-luna'); ?>"></td></tr><?php endif;?></table><?php submit_button('Save settings');?></form><hr><button class="button button-primary" id="alt-fixes-scan">Scan image library</button><div id="alt-fixes-results" style="margin-top:20px"></div></div><?php}
