<?php
/** OpenAI vision provider for Alt Fixes AI. */
if (!defined('ABSPATH')) exit;
class Alt_Fixes_OpenAI_Provider implements Alt_Fixes_Provider {
    private $api_key;
    private $model;
    public function __construct($api_key, $model = 'gpt-5.6-luna') { $this->api_key=trim((string)$api_key); $this->model=trim((string)$model)?:'gpt-5.6-luna'; }
    public function suggest($image_data_url, array $context = []) {
        if($this->api_key==='') return new WP_Error('missing_api_key','Configure an OpenAI API key first.',['status'=>400]);
        $response=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>90,'headers'=>['Authorization'=>'Bearer '.$this->api_key,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>$this->model,'input'=>[['role'=>'user','content'=>[['type'=>'input_text','text'=>$this->build_prompt($context)],['type'=>'input_image','image_url'=>$image_data_url]]]],'max_output_tokens'=>700])]);
        if(is_wp_error($response))return$response;
        $code=wp_remote_retrieve_response_code($response);$body=json_decode(wp_remote_retrieve_body($response),true);
        if($code>=400)return new WP_Error('provider_error',$body['error']['message']??'OpenAI request failed.',['status'=>502]);
        $text=$this->extract_text($body);if($text==='')return new WP_Error('empty_analysis','OpenAI returned no image analysis.',['status'=>502]);
        $analysis=json_decode($text,true);if(!is_array($analysis))return new WP_Error('invalid_analysis','The vision provider returned invalid analysis JSON.',['status'=>502]);
        $purpose=sanitize_key($analysis['purpose']??'informative');$allowed=['informative','decorative','logo','product','chart','diagram','screenshot','linked_control','text','complex'];if(!in_array($purpose,$allowed,true))$purpose='informative';
        $confidence=max(0,min(1,(float)($analysis['confidence']??.5)));$quality=max(0,min(100,(int)($analysis['quality_score']??50)));$decorative=!empty($analysis['decorative'])||$purpose==='decorative';$alt=sanitize_text_field((string)($analysis['alt']??''));$ocr=sanitize_textarea_field((string)($analysis['ocr_text']??''));
        $flags=[];foreach((array)($analysis['quality_flags']??[]) as$flag){$flag=sanitize_text_field($flag);if($flag!==''&&!in_array($flag,$flags,true))$flags[]=$flag;}
        return ['alt'=>$decorative?'':$alt,'purpose'=>$purpose,'decorative'=>$decorative,'confidence'=>$confidence,'quality_score'=>$quality,'quality_flags'=>$flags,'ocr_text'=>$ocr,'review_reason'=>sanitize_text_field((string)($analysis['review_reason']??'')),'evidence'=>sanitize_text_field((string)($analysis['evidence']??'')),'model'=>$this->model,'raw'=>$body];
    }
    private function build_prompt(array $context){$json=wp_json_encode($context,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return "You are an expert accessibility editor and visual QA system. Analyze image pixels plus WordPress context. Return JSON only with exactly these keys: alt, purpose, decorative, confidence, quality_score, quality_flags, ocr_text, review_reason, evidence.\n\nPurpose: informative, decorative, logo, product, chart, diagram, screenshot, linked_control, text, complex.\n\nAccessibility rules:\n- Judge the image's communicative purpose, not just objects.\n- Decorative or redundant imagery: alt=\"\", decorative=true.\n- Informative images: concise alt containing the essential information.\n- Functional/linked images: describe the action or destination, not appearance.\n- Logos: name the organization only when supported.\n- Images of meaningful text: preserve the relevant visible wording.\n- Charts, diagrams, maps and other complex visuals: give a concise identifying alt and flag the need for a longer accessible explanation when details matter. Never cram a data table into alt.\n- Do not invent facts.\n- Do not start alt with 'image of' or 'picture of'. Avoid redundant nearby text.\n\nQuality gate:\n- quality_score 0-100 estimates whether an accessibility editor can safely approve the proposed alt from available evidence.\n- Start from 100 and reduce for ambiguity, hallucination risk, missing context, unreadable text, excessive length, redundancy, weak purpose alignment, or complex information requiring a long description.\n- quality_flags is an array of short machine-readable flags. Use values such as low_confidence, unreadable_text, ambiguous_purpose, complex_visual, missing_context, likely_redundant, low_contrast, dense_chart, context_conflict, excessive_length, hallucination_risk.\n- confidence is 0-1.\n- review_reason is concise and non-empty whenever quality_score < 85, confidence < 0.85, or the image is complex/functional/text-heavy.\n- A high score does not override a complex-image review requirement.\n- ocr_text contains only meaningful readable text; empty if none.\n- evidence briefly states the visual/context evidence.\n\nWordPress context:\n".$json;}
    private function extract_text(array $body){if(!empty($body['output_text'])&&is_string($body['output_text']))return $this->clean_text($body['output_text']);foreach((array)($body['output']??[]) as$item)foreach((array)($item['content']??[]) as$content)if(!empty($content['text'])&&is_string($content['text']))return$this->clean_text($content['text']);return'';}
    private function clean_text($text){$text=trim((string)$text);$text=preg_replace('/^```(?:json)?\s*/i','',$text);$text=preg_replace('/\s*```$/','',$text);return trim($text);}
}
