<?php
/** Background job queue for AI image analysis. */
if (!defined('ABSPATH')) exit;

class Alt_Fixes_Queue {
    const TABLE_SUFFIX='alt_fixes_jobs'; const GROUP='alt-fixes-ai'; const HOOK='alt_fixes_process_job';
    const MAINTENANCE_HOOK='alt_fixes_queue_maintenance'; const CRON_HOOK='alt_fixes_queue_maintenance_cron';
    const DB_VERSION='1.1.0'; const MAX_ATTEMPTS=3; const STALE_TIMEOUT=900; const MAINTENANCE_INTERVAL=300;
    public static function table_name(){global $wpdb;return $wpdb->prefix.self::TABLE_SUFFIX;}
    public static function install(){global $wpdb;if(get_option('alt_fixes_db_version')===self::DB_VERSION)return;$table=self::table_name();$sql="CREATE TABLE {$table} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,attachment_id bigint(20) unsigned NOT NULL,status varchar(20) NOT NULL DEFAULT 'queued',active tinyint(1) unsigned NOT NULL DEFAULT 1,attempts tinyint(3) unsigned NOT NULL DEFAULT 0,error text NULL,created_at datetime NOT NULL,started_at datetime NULL,completed_at datetime NULL,PRIMARY KEY(id),KEY attachment_id(attachment_id),KEY status(status),KEY status_attachment(status,attachment_id),UNIQUE KEY attachment_active(attachment_id,active)) ".$wpdb->get_charset_collate().";";require_once ABSPATH.'wp-admin/includes/upgrade.php';dbDelta($sql);update_option('alt_fixes_db_version',self::DB_VERSION,false);}
    public static function schedule_maintenance(){if(function_exists('as_schedule_recurring_action')){if(function_exists('as_has_scheduled_action')){$scheduled=as_has_scheduled_action(self::MAINTENANCE_HOOK,[],self::GROUP);}else{$scheduled=function_exists('as_next_scheduled_action')&&as_next_scheduled_action(self::MAINTENANCE_HOOK,[],self::GROUP);}if(!$scheduled)as_schedule_recurring_action(time()+self::MAINTENANCE_INTERVAL,self::MAINTENANCE_INTERVAL,self::MAINTENANCE_HOOK,[],self::GROUP,true);return;}if(!wp_next_scheduled(self::CRON_HOOK))wp_schedule_event(time()+self::MAINTENANCE_INTERVAL,'five_minutes',self::CRON_HOOK);}
    public static function unschedule_maintenance(){if(function_exists('as_unschedule_all_actions'))as_unschedule_all_actions(self::MAINTENANCE_HOOK,[],self::GROUP);wp_clear_scheduled_hook(self::CRON_HOOK);}
    public static function enqueue($attachment_ids){global $wpdb;self::install();$ids=array_values(array_unique(array_filter(array_map('absint',(array)$attachment_ids))));$job_ids=[];foreach($ids as $attachment_id){if(!alt_fixes_validate_image($attachment_id))continue;$inserted=$wpdb->insert(self::table_name(),['attachment_id'=>$attachment_id,'status'=>'queued','active'=>1,'attempts'=>0,'created_at'=>current_time('mysql',true)],['%d','%s','%d','%d','%s']);if(!$inserted){$existing=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table_name()." WHERE attachment_id=%d AND active=1 ORDER BY id DESC LIMIT 1",$attachment_id));if($existing)$job_ids[]=(int)$existing;continue;}$job_id=(int)$wpdb->insert_id;if(!$job_id)continue;update_post_meta($attachment_id,'_alt_fixes_status','queued');$job_ids[]=$job_id;self::schedule($job_id);}return $job_ids;}
    private static function schedule($job_id,$delay=0){$timestamp=time()+max(0,(int)$delay);if(function_exists('as_enqueue_async_action')){if($delay>0&&function_exists('as_schedule_single_action'))as_schedule_single_action($timestamp,self::HOOK,[$job_id],self::GROUP,false);else as_enqueue_async_action(self::HOOK,[$job_id],self::GROUP,false);return;}wp_schedule_single_event($timestamp,self::HOOK,[$job_id]);}
    public static function process($job_id){global $wpdb;$table=self::table_name();$job_id=absint($job_id);if(!$job_id)return;$claimed=$wpdb->query($wpdb->prepare("UPDATE {$table} SET status='processing',attempts=attempts+1,started_at=%s,error=NULL WHERE id=%d AND status='queued'",current_time('mysql',true),$job_id));if(1!==(int)$claimed)return;$job=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d",$job_id),ARRAY_A);if(!$job)return;$attachment_id=(int)$job['attachment_id'];$attempts=(int)$job['attempts'];update_post_meta($attachment_id,'_alt_fixes_status','processing');if(!alt_fixes_validate_image($attachment_id)){self::fail($job_id,'The attachment is no longer a valid image.',$attempts,false);return;}$result=Alt_Fixes_Engine::suggest($attachment_id);if(is_wp_error($result)){self::fail($job_id,$result->get_error_message(),$attempts,$attempts<self::MAX_ATTEMPTS);return;}alt_fixes_store_suggestion($attachment_id,$result);$wpdb->update($table,['status'=>'completed','active'=>0,'error'=>null,'completed_at'=>current_time('mysql',true)],['id'=>$job_id,'status'=>'processing'],['%s','%d','%s','%s'],['%d','%s']);}
    private static function fail($job_id,$message,$attempts,$retry){global $wpdb;$table=self::table_name();$message=sanitize_text_field($message);if($retry){$wpdb->update($table,['status'=>'queued','error'=>$message,'started_at'=>null],['id'=>(int)$job_id,'status'=>'processing'],['%s','%s','%s'],['%d','%s']);self::schedule($job_id,min(300,30*(2**max(0,$attempts-1))));return;}$wpdb->update($table,['status'=>'failed','active'=>0,'error'=>$message,'completed_at'=>current_time('mysql',true)],['id'=>(int)$job_id,'status'=>'processing'],['%s','%d','%s','%s'],['%d','%s']);$attachment_id=(int)$wpdb->get_var($wpdb->prepare("SELECT attachment_id FROM {$table} WHERE id=%d",(int)$job_id));if($attachment_id)update_post_meta($attachment_id,'_alt_fixes_status','failed');}
    public static function recover_stale_jobs(){global $wpdb;$table=self::table_name();$cutoff=gmdate('Y-m-d H:i:s',time()-self::STALE_TIMEOUT);$jobs=$wpdb->get_results($wpdb->prepare("SELECT id,attachment_id,attempts FROM {$table} WHERE status='processing' AND started_at IS NOT NULL AND started_at<%s ORDER BY id ASC LIMIT 100",$cutoff),ARRAY_A);foreach($jobs as $job){$job_id=(int)$job['id'];$attachment_id=(int)$job['attachment_id'];$attempts=(int)$job['attempts'];if($attempts<self::MAX_ATTEMPTS){$updated=$wpdb->query($wpdb->prepare("UPDATE {$table} SET status='queued',started_at=NULL,error=%s WHERE id=%d AND status='processing'",'Recovered stale processing job; retrying automatically.',$job_id));if(1===(int)$updated){update_post_meta($attachment_id,'_alt_fixes_status','queued');self::schedule($job_id);}}else{$updated=$wpdb->query($wpdb->prepare("UPDATE {$table} SET status='failed',active=0,error=%s,completed_at=%s WHERE id=%d AND status='processing'",'Job timed out after the maximum number of attempts.',current_time('mysql',true),$job_id));if(1===(int)$updated)update_post_meta($attachment_id,'_alt_fixes_status','failed');}}}
    public static function get_progress($job_ids){global $wpdb;$ids=array_values(array_unique(array_filter(array_map('absint',(array)$job_ids))));if(!$ids)return['total'=>0,'queued'=>0,'processing'=>0,'completed'=>0,'failed'=>0];$ph=implode(',',array_fill(0,count($ids),'%d'));$rows=$wpdb->get_results($wpdb->prepare("SELECT status,COUNT(*) AS count FROM ".self::table_name()." WHERE id IN({$ph}) GROUP BY status",$ids),ARRAY_A);$p=['total'=>count($ids),'queued'=>0,'processing'=>0,'completed'=>0,'failed'=>0];foreach($rows as $r)if(isset($p[$r['status']]))$p[$r['status']]=(int)$r['count'];$p['done']=$p['completed']+$p['failed'];$p['percent']=$p['total']?(int)round($p['done']/$p['total']*100):0;return$p;}
    public static function get_jobs($job_ids){global $wpdb;$ids=array_values(array_unique(array_filter(array_map('absint',(array)$job_ids))));if(!$ids)return[];$ph=implode(',',array_fill(0,count($ids),'%d'));return$wpdb->get_results($wpdb->prepare("SELECT id,attachment_id,status,attempts,error,created_at,started_at,completed_at FROM ".self::table_name()." WHERE id IN({$ph}) ORDER BY id ASC",$ids),ARRAY_A);}
    public static function latest_job_for_attachment($attachment_id){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT id,status,attempts,error FROM ".self::table_name()." WHERE attachment_id=%d ORDER BY id DESC LIMIT 1",(int)$attachment_id),ARRAY_A);}
    public static function replace_scan_endpoint($endpoints){$route='/alt-fixes/v1/scan';if(isset($endpoints[$route][0]))$endpoints[$route][0]['callback']=[__CLASS__,'scan'];return$endpoints;}
    public static function scan(WP_REST_Request $request){global $wpdb;$page=max(1,absint($request->get_param('page'))?:1);$per_page=min(100,max(1,absint($request->get_param('per_page'))?:24));$status=sanitize_key($request->get_param('status')?:'all');$allowed=['all','missing','queued','processing','suggested','approved','skipped','failed'];if(!in_array($status,$allowed,true))$status='all';$posts=$wpdb->posts;$meta=$wpdb->postmeta;$joins='';$where="p.post_type='attachment' AND p.post_status='inherit' AND p.post_mime_type LIKE 'image/%'";$args=[];if($status!=='all'){$joins=" LEFT JOIN {$meta} AS status_meta ON status_meta.post_id=p.ID AND status_meta.meta_key='_alt_fixes_status' LEFT JOIN {$meta} AS alt_meta ON alt_meta.post_id=p.ID AND alt_meta.meta_key='_wp_attachment_image_alt' LEFT JOIN {$meta} AS suggestion_meta ON suggestion_meta.post_id=p.ID AND suggestion_meta.meta_key='_alt_fixes_suggestion'";switch($status){case'missing':$where.=" AND COALESCE(status_meta.meta_value,'')='' AND COALESCE(alt_meta.meta_value,'')='' AND COALESCE(suggestion_meta.meta_value,'')=''";break;case'suggested':$where.=" AND (status_meta.meta_value='suggested' OR (COALESCE(status_meta.meta_value,'')='' AND COALESCE(alt_meta.meta_value,'')='' AND COALESCE(suggestion_meta.meta_value,'')<>''))";break;case'approved':$where.=" AND (status_meta.meta_value='approved' OR (COALESCE(status_meta.meta_value,'')='' AND COALESCE(alt_meta.meta_value,'')<>''))";break;default:$where.=' AND status_meta.meta_value=%s';$args[]=$status;}}$count_sql="SELECT COUNT(DISTINCT p.ID) FROM {$posts} AS p {$joins} WHERE {$where}";$prepared_count=$args?$wpdb->prepare($count_sql,$args):$count_sql;$total=(int)$wpdb->get_var($prepared_count);$pages=$total?(int)ceil($total/$per_page):0;$offset=($page-1)*$per_page;$id_sql="SELECT DISTINCT p.ID FROM {$posts} AS p {$joins} WHERE {$where} ORDER BY p.ID DESC LIMIT %d OFFSET %d";$id_args=$args;$id_args[]=$per_page;$id_args[]=$offset;$page_ids=$wpdb->get_col($wpdb->prepare($id_sql,$id_args));$items=[];foreach($page_ids as $id){$alt=(string)get_post_meta($id,'_wp_attachment_image_alt',true);$suggestion=(string)get_post_meta($id,'_alt_fixes_suggestion',true);$analysis=get_post_meta($id,'_alt_fixes_analysis',true);$job=self::latest_job_for_attachment($id);$items[]=['id'=>(int)$id,'title'=>get_the_title($id),'url'=>wp_get_attachment_image_url($id,'medium'),'alt'=>$alt,'suggestion'=>$suggestion,'status'=>alt_fixes_get_status($id,$alt,$suggestion),'purpose'=>is_array($analysis)?($analysis['purpose']??null):null,'confidence'=>is_array($analysis)&&isset($analysis['confidence'])?(float)$analysis['confidence']:null,'review_reason'=>is_array($analysis)?($analysis['review_reason']??''):'','error'=>$job?(string)($job['error']??''):'','job_id'=>$job?(int)$job['id']:null,'attempts'=>$job?(int)$job['attempts']:0];}return rest_ensure_response(['items'=>$items,'page'=>$page,'per_page'=>$per_page,'total'=>$total,'pages'=>$pages]);}
}
add_action(Alt_Fixes_Queue::HOOK,['Alt_Fixes_Queue','process']);add_action(Alt_Fixes_Queue::MAINTENANCE_HOOK,['Alt_Fixes_Queue','recover_stale_jobs']);add_action(Alt_Fixes_Queue::CRON_HOOK,['Alt_Fixes_Queue','recover_stale_jobs']);add_filter('rest_endpoints',['Alt_Fixes_Queue','replace_scan_endpoint']);
add_filter('cron_schedules',function($schedules){if(!isset($schedules['five_minutes']))$schedules['five_minutes']=['interval'=>300,'display'=>'Every Five Minutes'];return$schedules;});
