<?php
/** Lightweight site-local learning, correction analytics, site-specific rules, and correction replay. */
if (!defined('ABSPATH')) exit;
class Alt_Fixes_Learning {
    const OPTION='alt_fixes_learning'; const LIMIT=100;
    public static function boot(){add_action('updated_post_meta',[__CLASS__,'capture'],10,4);add_action('added_post_meta',[__CLASS__,'capture'],10,4);add_action('admin_footer',[__CLASS__,'render_learning_lab']);}
    public static function capture($meta_id,$post_id,$meta_key,$meta_value){
        if($meta_key!=='_wp_attachment_image_alt'||!wp_attachment_is_image($post_id))return;
        $approved=sanitize_text_field((string)$meta_value);if($approved==='')return;
        $generated=sanitize_text_field((string)get_post_meta($post_id,'_alt_fixes_suggestion',true));if($generated==='')return;
        $analysis=get_post_meta($post_id,'_alt_fixes_analysis',true);$analysis=is_array($analysis)?$analysis:[];
        $entry=['generated'=>$generated,'approved'=>$approved,'edited'=>self::normalize($generated)!==self::normalize($approved),'purpose'=>sanitize_key($analysis['purpose']??'informative'),'flags'=>array_slice(array_map('sanitize_key',(array)($analysis['quality_flags']??[])),0,8),'at'=>current_time('mysql',true)];
        $learning=get_option(self::OPTION,[]);if(!is_array($learning))$learning=[];$learning['corrections']=array_values((array)($learning['corrections']??[]));$learning['corrections'][]=$entry;if(count($learning['corrections'])>self::LIMIT)$learning['corrections']=array_slice($learning['corrections'],-self::LIMIT);
        $learning['stats']=['approvals'=>(int)($learning['stats']['approvals']??0)+1,'edits'=>(int)($learning['stats']['edits']??0)+($entry['edited']?1:0),'auto_approvals'=>(int)($learning['stats']['auto_approvals']??0)];update_option(self::OPTION,$learning,false);
    }
    public static function record_auto_approval(){
        $learning=get_option(self::OPTION,[]);if(!is_array($learning))$learning=[];$stats=(array)($learning['stats']??[]);$stats['approvals']=(int)($stats['approvals']??0);$stats['edits']=(int)($stats['edits']??0);$stats['auto_approvals']=(int)($stats['auto_approvals']??0)+1;$learning['stats']=$stats;update_option(self::OPTION,$learning,false);
    }
    public static function analytics(){
        $learning=get_option(self::OPTION,[]);$rows=array_values((array)($learning['corrections']??[]));$stats=(array)($learning['stats']??[]);$approvals=(int)($stats['approvals']??0);$edits=(int)($stats['edits']??0);$auto=(int)($stats['auto_approvals']??0);$purpose=[];$flags=[];$recent=[];
        foreach(array_reverse($rows) as $row){if(!is_array($row))continue;$p=sanitize_key($row['purpose']??'informative');$purpose[$p]=($purpose[$p]??0)+1;foreach((array)($row['flags']??[]) as $f){$f=sanitize_key($f);if($f)$flags[$f]=($flags[$f]??0)+1;}if(count($recent)<10)$recent[]=['edited'=>!empty($row['edited']),'purpose'=>$p,'generated'=>sanitize_text_field($row['generated']??''),'approved'=>sanitize_text_field($row['approved']??''),'flags'=>array_slice(array_map('sanitize_key',(array)($row['flags']??[])),0,8),'at'=>sanitize_text_field($row['at']??'')];}
        arsort($purpose);arsort($flags);
        return['sample_size'=>count($rows),'approvals'=>$approvals,'edits'=>$edits,'edit_rate'=>$approvals?round($edits/$approvals*100,1):0,'unchanged_rate'=>$approvals?round(($approvals-$edits)/$approvals*100,1):0,'auto_approvals'=>$auto,'auto_approval_rate'=>($approvals+$auto)?round($auto/($approvals+$auto)*100,1):0,'purpose_breakdown'=>$purpose,'common_flags'=>array_slice($flags,0,8,true),'recent'=>$recent,'site_rules'=>self::rules($rows)];
    }
    public static function for_prompt($context=[]){
        $learning=get_option(self::OPTION,[]);$rows=array_values((array)($learning['corrections']??[]));if(!$rows)return['available'=>false,'examples'=>[],'site_rules'=>[],'stats'=>(array)($learning['stats']??[])];
        $examples=[];foreach(array_reverse($rows) as $row){if(!is_array($row)||empty($row['approved']))continue;$examples[]=['purpose'=>sanitize_key($row['purpose']??'informative'),'generated'=>sanitize_text_field($row['generated']??''),'human_approved'=>sanitize_text_field($row['approved']??''),'edited'=>!empty($row['edited']),'flags'=>array_slice(array_map('sanitize_key',(array)($row['flags']??[])),0,6)];if(count($examples)>=8)break;}
        return['available'=>!empty($examples),'site_context'=>['parent_title'=>sanitize_text_field($context['parent']['title']??''),'headings'=>array_slice(array_map('sanitize_text_field',(array)($context['parent']['headings']??[])),0,5)],'site_rules'=>self::rules($rows),'examples'=>$examples,'stats'=>(array)($learning['stats']??[])];
    }
    public static function render_learning_lab(){
        if(!is_admin()||empty($_GET['page'])||sanitize_key(wp_unslash($_GET['page']))!=='alt-fixes'||!current_user_can('manage_options'))return;
        $data=self::analytics();$recent=array_values(array_filter((array)$data['recent'],function($r){return !empty($r['edited']);}));$rules=$data['site_rules'];
        echo '<section id="alt-fixes-learning-lab" class="alt-fixes-learning-lab"><div class="alt-fixes-learning-lab-head"><div><h2>Correction Replay / AI Learning Lab</h2><p>Replay human edits to see exactly what changed, which pattern the system detected, and how that pattern will influence future suggestions. This does not treat old wording as facts about new images.</p></div><span>'.esc_html(count($recent)).' edited corrections</span></div>';
        if(!$recent){echo '<div class="alt-fixes-learning-empty"><strong>No edited corrections to replay yet.</strong><span>Generate suggestions, edit them before approval, and the learning lab will build a replayable history.</span></div></section>';return;}
        echo '<div class="alt-fixes-learning-list">';foreach($recent as $index=>$row){$generated=(string)($row['generated']??'');$approved=(string)($row['approved']??'');$g=self::tokens($generated);$a=self::tokens($approved);$removed=array_values(array_diff($g,$a));$added=array_values(array_diff($a,$g));$id='alt-fixes-replay-'.$index;
            echo '<details class="alt-fixes-replay"><summary><span>'.esc_html(ucwords(str_replace('_',' ',(string)$row['purpose']))).'</span><strong>'.esc_html($generated).' → '.esc_html($approved).'</strong><time>'.esc_html($row['at']??'').'</time></summary><div class="alt-fixes-replay-body"><div class="alt-fixes-replay-columns"><div><h4>AI generated</h4><p>'.esc_html($generated).'</p></div><div><h4>Human approved</h4><p>'.esc_html($approved).'</p></div></div><div class="alt-fixes-replay-change"><div><h4>Removed by humans</h4><div>'.($removed?implode('',array_map(function($w){return '<span class="is-removed">'.esc_html($w).'</span>';$w;},$removed)):'<span class="is-none">None</span>').'</div></div><div><h4>Added by humans</h4><div>'.($added?implode('',array_map(function($w){return '<span class="is-added">'.esc_html($w).'</span>';$w;},$added)):'<span class="is-none">None</span>').'</div></div></div><div class="alt-fixes-replay-impact"><h4>How this correction teaches the system</h4><p>Purpose: <strong>'.esc_html($row['purpose']??'informative').'</strong>. The correction contributes to recurring writing patterns only after enough edited examples exist.</p><div class="alt-fixes-replay-rules">'.($rules?implode('',array_map(function($k,$v){$value=is_array($v)?implode(', ',array_map('sanitize_text_field',$v)):((string)$v);return '<span><strong>'.esc_html(ucwords(str_replace('_',' ',$k))).':</strong> '.esc_html($value).'</span>';},array_keys($rules),array_values($rules))):'<span>Learning rules are still forming.</span>').'</div><p class="alt-fixes-learning-note">Future generation may use these rules as soft style guidance, but current image evidence, page context and accessibility requirements always take priority.</p></div>'.(!empty($row['flags'])?'<div class="alt-fixes-replay-flags"><strong>Quality signals:</strong> '.esc_html(implode(', ',$row['flags'])).'</div>':'').'</div></details>';
        }echo '</div></section><style>.alt-fixes-learning-lab{margin:24px 0;padding:24px;background:#fff;border:1px solid #dcdcde;border-radius:10px}.alt-fixes-learning-lab-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.alt-fixes-learning-lab h2{margin:0 0 6px}.alt-fixes-learning-lab p{margin:4px 0;color:#50575e}.alt-fixes-learning-lab-head>span{white-space:nowrap;padding:7px 10px;border-radius:999px;background:#f0f6fc}.alt-fixes-learning-empty{margin-top:18px;padding:20px;border:1px dashed #c3c4c7;border-radius:8px;display:grid;gap:5px}.alt-fixes-learning-list{margin-top:18px;display:grid;gap:10px}.alt-fixes-replay{border:1px solid #dcdcde;border-radius:8px;background:#fbfbfc;overflow:hidden}.alt-fixes-replay summary{cursor:pointer;padding:14px 16px;display:grid;grid-template-columns:150px minmax(0,1fr) auto;gap:14px;align-items:center}.alt-fixes-replay summary>span{font-size:12px;font-weight:600;text-transform:uppercase}.alt-fixes-replay summary>strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.alt-fixes-replay summary time{font-size:12px;color:#646970}.alt-fixes-replay-body{padding:0 16px 16px}.alt-fixes-replay-columns{display:grid;grid-template-columns:1fr 1fr;gap:12px}.alt-fixes-replay-columns>div,.alt-fixes-replay-impact{padding:14px;background:#fff;border:1px solid #e2e4e7;border-radius:7px}.alt-fixes-replay h4{margin:0 0 7px}.alt-fixes-replay-change{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.alt-fixes-replay-change>div{padding:12px;background:#fff;border:1px solid #e2e4e7;border-radius:7px}.alt-fixes-replay-change span{display:inline-block;margin:2px 4px 2px 0;padding:4px 7px;border-radius:5px;font-size:12px}.alt-fixes-replay-change .is-removed{background:#fbeaea;text-decoration:line-through}.alt-fixes-replay-change .is-added{background:#eaf7ed}.alt-fixes-replay-change .is-none{color:#646970}.alt-fixes-replay-impact{margin-top:12px}.alt-fixes-replay-rules{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.alt-fixes-replay-rules span{padding:7px 9px;background:#f6f7f7;border-radius:6px;font-size:12px}.alt-fixes-learning-note{font-size:12px!important;margin-top:12px!important}.alt-fixes-replay-flags{margin-top:10px;font-size:12px;color:#646970}@media(max-width:800px){.alt-fixes-learning-lab-head,.alt-fixes-replay-columns,.alt-fixes-replay-change{display:block}.alt-fixes-replay-columns>div,.alt-fixes-replay-change>div{margin-top:10px}.alt-fixes-replay summary{grid-template-columns:1fr}.alt-fixes-replay summary>strong{white-space:normal}}</style>';
    }
    private static function rules(array $rows){
        $edited=array_values(array_filter($rows,function($r){return is_array($r)&&!empty($r['edited'])&&!empty($r['generated'])&&!empty($r['approved']);}));
        if(count($edited)<3)return[];
        $lengths=[];$added=[];$removed=[];$purpose_lengths=[];
        foreach($edited as $row){$g=self::tokens($row['generated']);$a=self::tokens($row['approved']);$lengths[]=count($a);$p=sanitize_key($row['purpose']??'informative');$purpose_lengths[$p][] = count($a);foreach(array_diff($a,$g) as $word)$added[$word]=($added[$word]??0)+1;foreach(array_diff($g,$a) as $word)$removed[$word]=($removed[$word]??0)+1;}
        arsort($added);arsort($removed);$rules=[];$n=count($edited);$median=self::median($lengths);
        if($median>0)$rules['preferred_alt_words']=$median;
        $rules['avoid_terms']=array_keys(array_filter($removed,function($count)use($n){return $count>=max(2,(int)ceil($n*.25));}));
        $rules['preferred_terms']=array_keys(array_filter($added,function($count)use($n){return $count>=max(2,(int)ceil($n*.25));}));
        foreach($purpose_lengths as $purpose=>$vals)if(count($vals)>=2)$rules['preferred_words_by_purpose'][$purpose]=self::median($vals);
        if(!empty($rules['preferred_terms']))$rules['preferred_terms']=array_slice($rules['preferred_terms'],0,12);
        if(!empty($rules['avoid_terms']))$rules['avoid_terms']=array_slice($rules['avoid_terms'],0,12);
        return$rules;
    }
    private static function tokens($value){$value=preg_replace('/[^\pL\pN\s-]+/u',' ',strtolower((string)$value));$parts=preg_split('/\s+/u',trim($value));$stop=['the','a','an','of','and','in','on','for','to','with','is','are'];return array_values(array_unique(array_filter($parts,function($w)use($stop){return $w!==''&&!in_array($w,$stop,true)&&mb_strlen($w)>=3;})));}
    private static function median(array $values){sort($values,SORT_NUMERIC);$n=count($values);if(!$n)return 0;$m=(int)floor($n/2);return$n%2?$values[$m]:round(($values[$m-1]+$values[$m])/2);}
    private static function normalize($value){return preg_replace('/\s+/u',' ',strtolower(trim((string)$value)));}
}
Alt_Fixes_Learning::boot();
